[ACTUALIZACION]
Ejecutable=solcvn.exe
Fecha=14/02/2012 11:00
Path=C:\SISTEMAS\entrega_documentos
SOURCE=\\mantencion_2000\last_version\entrega_documentos

[INSTALACION]
Path=C:\SISTEMAS\entrega_documentos
update=
SOURCE=\\mantencion_2000\last_version\entrega_documentos

[Connect]
Servidor=150.10.10.99
;Servidor=150.10.10.5\REPLICA
;Servidor=srv-nmv-qa01.masvida.cl
BaseDato=ISAPRE
age_codigo=800

[User Info]
UltimoLogin=LVIVANCOM

[Huella]
dns_odbc=sql_huella_emision
Servidor = 150.10.10.57
BaseDatos = AGENCIAS
imagen=huella.bmp
compartido=N
hamster=1

[MEJORAS]
Num=1
[solcvn consulta]
estados=I
fecha_desde=
fecha_hasta=
rut_prestador=
agencia=
