USE [ISAPRE]
GO

/****** Object:  Table [dbo].[GCO_ENVMSG_CONCEPTO]    Script Date: 02-10-2025 14:32:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GCO_ENVMSG_CONCEPTO](
	[ECO_CODIGO] [numeric](5, 0) NOT NULL,
	[ECO_NOMBRE] [varchar](200) NOT NULL,
	[ECO_TIPO_SELECCION] [char](1) NOT NULL,
 CONSTRAINT [PK_GCO_ENVMSG_CONCEPTO] PRIMARY KEY CLUSTERED 
(
	[ECO_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GCO_ENVMSG_CONCEPTO]  WITH CHECK ADD  CONSTRAINT [CKC_ECO_TIPO_SELECCIO_GCO_ENVM] CHECK  (([ECO_TIPO_SELECCION]='M' OR [ECO_TIPO_SELECCION]='S'))
GO

ALTER TABLE [dbo].[GCO_ENVMSG_CONCEPTO] CHECK CONSTRAINT [CKC_ECO_TIPO_SELECCIO_GCO_ENVM]
GO


