USE [ISAPRE]
GO

/****** Object:  Table [dbo].[GCO_ENVMSG_FILTRO]    Script Date: 02-10-2025 14:33:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GCO_ENVMSG_FILTRO](
	[EPL_CODIGO] [varchar](50) NOT NULL,
	[ECO_CODIGO] [numeric](5, 0) NOT NULL,
	[EFI_VALOR] [varchar](4000) NOT NULL,
 CONSTRAINT [PK_GCO_ENVMSG_FILTRO] PRIMARY KEY CLUSTERED 
(
	[EPL_CODIGO] ASC,
	[ECO_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GCO_ENVMSG_FILTRO]  WITH CHECK ADD  CONSTRAINT [FK_GCO_ENVM_REF_10501_GCO_ENVM1] FOREIGN KEY([EPL_CODIGO])
REFERENCES [dbo].[GCO_ENVMSG_PLANTILLA] ([EPL_CODIGO])
GO

ALTER TABLE [dbo].[GCO_ENVMSG_FILTRO] CHECK CONSTRAINT [FK_GCO_ENVM_REF_10501_GCO_ENVM1]
GO

ALTER TABLE [dbo].[GCO_ENVMSG_FILTRO]  WITH CHECK ADD  CONSTRAINT [FK_GCO_ENVM_REF_10501_GCO_ENVM2] FOREIGN KEY([ECO_CODIGO])
REFERENCES [dbo].[GCO_ENVMSG_CONCEPTO] ([ECO_CODIGO])
GO

ALTER TABLE [dbo].[GCO_ENVMSG_FILTRO] CHECK CONSTRAINT [FK_GCO_ENVM_REF_10501_GCO_ENVM2]
GO



--GRANT INSERT, UPDATE, DELETE ON [GCO_ENVMSG_FILTRO] TO public;
