USE [ISAPRE]
GO

/****** Object:  Table [dbo].[GCO_ENVMSG_PLANTILLA]    Script Date: 02-10-2025 14:34:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GCO_ENVMSG_PLANTILLA](
	[EPL_CODIGO] [varchar](50) NOT NULL,
	[EPL_NOMBRE] [varchar](500) NOT NULL,
	[EPL_VIGENTE] [char](1) NOT NULL,
 CONSTRAINT [PK_GCO_ENVMSG_PLANTILLA] PRIMARY KEY CLUSTERED 
(
	[EPL_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GCO_ENVMSG_PLANTILLA] ADD  DEFAULT ('N') FOR [EPL_VIGENTE]
GO

ALTER TABLE [dbo].[GCO_ENVMSG_PLANTILLA]  WITH CHECK ADD  CONSTRAINT [CKC_EPL_VIGENTE_GCO_ENVM] CHECK  (([EPL_VIGENTE]='N' OR [EPL_VIGENTE]='S'))
GO

ALTER TABLE [dbo].[GCO_ENVMSG_PLANTILLA] CHECK CONSTRAINT [CKC_EPL_VIGENTE_GCO_ENVM]
GO


----GRANT INSERT, UPDATE, DELETE ON [GCO_ENVMSG_PLANTILLA] TO public;

