USE [ISAPRE]
GO

/****** Object:  Table [dbo].[GCO_ENVMSG_API_TEMPLATE]    Script Date: 02-10-2025 14:33:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GCO_ENVMSG_API_TEMPLATE](
	[ATE_CODIGO] [numeric](5, 0) NOT NULL,
	[ATE_CODIGO_API] [varchar](100) NOT NULL,
	[ATE_DESCRIPCION] [varchar](200) NOT NULL,
 CONSTRAINT [PK_GCO_ENVMSG_API_TEMPLATE] PRIMARY KEY CLUSTERED 
(
	[ATE_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


