USE ISAPRE
GO

SELECT SPP_FOLIO
      ,SPP_FECHA
      ,SPP_RUT
      ,SPP_NOMBRE
      ,SPP_DIRECCION
      ,SPP_EMAIL
      ,SPP_USUARIO
      ,SPP_TIPO
      ,SPP_FORMA_PAGO
      ,BCO_CODIGO
      ,TIPO_CTA
      ,SPP_NUMCTACTE
      ,SPP_SALDO_RESTITUCION_UF
      ,SPP_SALDO_RESTITUCION_PESOS
      ,SPP_DEUDA_COTIZ
      ,SPP_DEUDA_LUR
      ,SPP_HONCOB
      ,SPP_SALDO_POST_COMPENS
      ,SPP_TASA_DCTO
      ,SPP_MONTO_DCTO
      ,SPP_TOTAL_APAGAR
      ,SPP_FECHA_AUTORIZA
      ,SPP_FECHA_PAGO
      ,SPP_PIN
  FROM dbo.SOLIC_PRONTO_PAGO_TFU

GO


