-- ==========================================================  
-- Author:  Alberto Rozas  
-- Create date: 06-07-2022  
-- Description: Consulta la deuda de una Resolución Judicial. 

-- Modificación:  Jorge Molina  
-- Create date: 18-03-2026  
-- Description: Tareas #17675: se cambia tabla RJUD_DEUDA por DEUDA_COTIZANTE 
-- ==========================================================  

-- exec spu_ges_cob_consdeuda_judicial 18325  
-- exec spu_ges_cob_consdeuda_judicial 6024

ALTER PROCEDURE spu_ges_cob_consdeuda_judicial @rej_folio NUMERIC(10)   
AS  
BEGIN   
 SET NOCOUNT ON;  
  
  --V0- COMENTAR, REVISAR V1, si esta bien V1 -> ELIMINAR V0
 --   SELECT SUM(RJD.RJD_DEUDA) AS DEUDANOMINAL,  
 --  SUM(ROUND((CASE WHEN (INT.INT_REAJUSTE < 0) OR (INT.INT_REAJUSTE IS NULL) THEN 0 ELSE INT.INT_REAJUSTE END) / 100 * (COALESCE(RJD.RJD_DEUDA, 0)), 0)) AS REAJUSTE,  
 --  SUM(ROUND((CASE WHEN (INT.INT_INTERES < 0) OR (INT.INT_INTERES IS NULL) THEN 0 ELSE INT.INT_INTERES END) / 100 * (COALESCE(RJD.RJD_DEUDA, 0)), 0)) AS INTERES,  
 --  SUM(ROUND((CASE WHEN (INT.INT_RECARGO < 0) OR (INT.INT_RECARGO IS NULL) THEN 0 ELSE INT.INT_RECARGO END) / 100 * (COALESCE(RJD.RJD_DEUDA, 0)), 0)) AS RECARGO  
 --FROM RESOLUCION_JUDICIAL REJ WITH (NOLOCK)  
 --  JOIN RJUD_DEUDA RJD WITH (NOLOCK) ON RJD.REJ_FOLIO = REJ.REJ_FOLIO    
 --  LEFT JOIN INTERESES INT WITH (NOLOCK) ON INT.INT_PPC_PERIODO = RJD.RJD_PERIODO AND INT.INT_FECHA_PAGO = CONVERT(CHAR(8), GETDATE(), 112)  
 --WHERE REJ.REJ_FOLIO = @rej_folio  


 --V1
 --RJD.RJD_DEUDA = (ISNULL(DEC_PACTADO, 0) - ISNULL(DEC_PAGADO, 0))

     SELECT SUM((ISNULL(DEC_PACTADO, 0) - ISNULL(DEC_PAGADO, 0))) AS DEUDANOMINAL,  
   SUM(ROUND((CASE WHEN (INT.INT_REAJUSTE < 0) OR (INT.INT_REAJUSTE IS NULL) THEN 0 ELSE INT.INT_REAJUSTE END) / 100 * (COALESCE((ISNULL(DEC_PACTADO, 0) - ISNULL(DEC_PAGADO, 0)), 0)), 0)) AS REAJUSTE,  
   SUM(ROUND((CASE WHEN (INT.INT_INTERES < 0) OR (INT.INT_INTERES IS NULL) THEN 0 ELSE INT.INT_INTERES END) / 100 * (COALESCE((ISNULL(DEC_PACTADO, 0) - ISNULL(DEC_PAGADO, 0)), 0)), 0)) AS INTERES,  
   SUM(ROUND((CASE WHEN (INT.INT_RECARGO < 0) OR (INT.INT_RECARGO IS NULL) THEN 0 ELSE INT.INT_RECARGO END) / 100 * (COALESCE((ISNULL(DEC_PACTADO, 0) - ISNULL(DEC_PAGADO, 0)), 0)), 0)) AS RECARGO  
 FROM RESOLUCION_JUDICIAL REJ WITH (NOLOCK)  
   JOIN DEUDA_COTIZANTE RJD WITH (NOLOCK) ON RJD.DEC_NRORESOL = REJ.REJ_FOLIO    
   LEFT JOIN INTERESES INT WITH (NOLOCK) ON INT.INT_PPC_PERIODO = RJD.DEC_PERIODO AND INT.INT_FECHA_PAGO = CONVERT(CHAR(8), GETDATE(), 112)  
 WHERE REJ.REJ_FOLIO = @rej_folio

END  