USE [ISAPRE]
GO

/****** Object:  Table [dbo].[DEUDOR]    Script Date: 17-12-2025 20:23:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEUDOR](
	[DDR_RUT] [char](10) NOT NULL,
	[DDR_NOMBRE] [varchar](250) NOT NULL,
	[DDR_DIRECCION] [varchar](250) NULL,
	[DDR_DIRECCION2] [varchar](250) NULL,
	[CIU_CODIGO] [numeric](4, 0) NULL,
	[CMN_CODIGO] [numeric](4, 0) NULL,
	[DDR_TELEFONO] [char](50) NULL,
	[DDR_EMAIL] [varchar](50) NULL,
	[DDR_INF_CONTACTO] [varchar](250) NULL,
	[DDR_CELULAR] [varchar](50) NULL,
	[DDR_GIRO] [varchar](100) NULL,
	[DDR_RUT_REPR] [char](10) NULL,
	[DDR_NOM_REPR] [varchar](250) NULL,
	[DDR_TIPO_REPR] [char](1) NULL,
	[RAC_CODIGO] [numeric](10, 0) NULL,
	[TDE_CODIGO] [char](5) NULL,
	[DDR_QUIEBRA] [char](1) NULL,
	[DDR_MEDIATICA] [char](1) NULL,
 CONSTRAINT [PK_DEUDOR] PRIMARY KEY CLUSTERED 
(
	[DDR_RUT] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DEUDOR] ADD  CONSTRAINT [DF__DEUDOR__DDR_TIPO__78260C6F]  DEFAULT ('L') FOR [DDR_TIPO_REPR]
GO

ALTER TABLE [dbo].[DEUDOR] ADD  DEFAULT ('N') FOR [DDR_QUIEBRA]
GO

ALTER TABLE [dbo].[DEUDOR] ADD  DEFAULT ('N') FOR [DDR_MEDIATICA]
GO

ALTER TABLE [dbo].[DEUDOR]  WITH CHECK ADD  CONSTRAINT [FK_DEUDOR_REF_10329_TIPO_DEU] FOREIGN KEY([TDE_CODIGO])
REFERENCES [dbo].[TIPO_DEUDOR] ([TDE_CODIGO])
GO

ALTER TABLE [dbo].[DEUDOR] CHECK CONSTRAINT [FK_DEUDOR_REF_10329_TIPO_DEU]
GO

ALTER TABLE [dbo].[DEUDOR]  WITH NOCHECK ADD  CONSTRAINT [FK_DEUDOR_REF_56646_CIUDAD] FOREIGN KEY([CIU_CODIGO])
REFERENCES [dbo].[CIUDAD] ([CIU_CODIGO])
GO

ALTER TABLE [dbo].[DEUDOR] CHECK CONSTRAINT [FK_DEUDOR_REF_56646_CIUDAD]
GO

ALTER TABLE [dbo].[DEUDOR]  WITH CHECK ADD  CONSTRAINT [FK_DEUDOR_REF_56646_COMUNA] FOREIGN KEY([CMN_CODIGO])
REFERENCES [dbo].[COMUNA] ([CMN_CODIGO])
GO

ALTER TABLE [dbo].[DEUDOR] CHECK CONSTRAINT [FK_DEUDOR_REF_56646_COMUNA]
GO

ALTER TABLE [dbo].[DEUDOR]  WITH CHECK ADD  CONSTRAINT [CKC_DDR_TIPO_REPR_DEUDOR] CHECK  (([DDR_TIPO_REPR]='S' OR [DDR_TIPO_REPR]='L'))
GO

ALTER TABLE [dbo].[DEUDOR] CHECK CONSTRAINT [CKC_DDR_TIPO_REPR_DEUDOR]
GO


