USE [ISAPRE]
GO

/****** Object:  Table [dbo].[CONTACTO_DET_NEW_FINAL]    Script Date: 03-12-2024 17:11:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTACTO_DET_NEW_FINAL](
	[CTO_RUT] [char](10) NOT NULL,
	[CTD_CORREL] [numeric](15, 0) NOT NULL,
	[CTD_DIRECCION] [varchar](250) NULL,
	[CTD_DIRECCION_V2] [varchar](250) NULL,
	[CMN_CODIGO] [numeric](4, 0) NULL,
	[CTD_EMAIL1] [varchar](250) NULL,
	[CTD_EMAIL2] [varchar](250) NULL,
	[CTD_FONO1] [varchar](50) NULL,
	[CTD_FONO2] [varchar](50) NULL,
	[CTD_ENCAR_REM] [varchar](250) NULL,
	[USU_LOGIN] [char](30) NOT NULL,
	[CTD_FECREG] [datetime] NULL,
	[CTD_ORIGEN] [varchar](50) NOT NULL,
	[CTD_INF_CONTACTO] [varchar](250) NULL,
	[CTD_TIPO_VAL] [char](1) NULL,
	[USU_LOGIN_VAL] [varchar](100) NULL,
	[CTD_FECHA_VAL] [datetime] NULL,
	[CTD_ORIGEN_VAL] [varchar](200) NULL,
	[CONCEPTO] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[CTO_RUT] ASC,
	[CTD_CORREL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO


