USE [ISAPRE]
GO

/****** Object:  Table [dbo].[GCO_ENVMSG_DEUDA_CUPONES_DEUFIN]    Script Date: 29-12-2025 12:20:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GCO_ENVMSG_DEUDA_CUPONES_DEUFIN](
	[CUP_ID_BASE] [datetime] NOT NULL,
	[COT_RUT] [char](10) NOT NULL,
	[NOM_DEUDOR] [varchar](200) NULL,
	[DEU_CORREL] [numeric](15, 0) NULL,
	[DEU_MONTO] [numeric](15, 0) NULL,
	[DEU_DESCUENTO] [numeric](15, 0) NULL
) ON [PRIMARY]
GO


--GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::dbo.GCO_ENVMSG_DEUDA_CUPONES_DEUFIN TO public;
