-- ==========================================================  
-- Author:  Alberto Rozas  
-- Create date: 21-09-2021   
-- Description: Entrega datos de la Cartera de Deuda Detalle.  
-- ==========================================================  
-- Modificado por:  Marcelo Sanhueza  
-- Create date: 31-10-2023   
-- Description: Se agregan los datos del predictor de pago.  
-- ==========================================================  
--EXEC spu_ges_cob_cartera_deuda_detalle 1, 11  
CREATE PROCEDURE [dbo].[spu_ges_cob_cartera_deuda_detalle] @cob_codigo NUMERIC(4), @clasif INT  
AS  
BEGIN  
  
 /*  
 @clasif:  
   Tipo Deudor  
   11 Afiliado  
   12 Empresa  
   13 Empresa pública  
     
   Tipo Deuda  
   21 DNP  
   22 NP  
   23 IP  
  
   Tipo Contrato  
   31 Independiente  
   32 Voluntario  
   33 Dependiente  
   34 Pensionado  
  
   Estado Vigencia de Contrato  
   41 Vigente  
   42 No vigente  
 */  
  
 SET NOCOUNT ON;  
  
 IF OBJECT_ID('tempdb..#DEUDA_DB') IS NOT NULL  
  DROP TABLE #DEUDA_DB  
  
 CREATE TABLE #DEUDA_DB  
  (DDR_RUT   CHAR(10)  NULL,  
  DEU_ASIG_DESDE  DATETIME  NULL,  
  TIPO_CON_ACTUAL  VARCHAR(250) NULL,  
  ESTADO_VIG_CONTRATO VARCHAR(20)  NULL,  
  TIPO_DEUDA   VARCHAR(3)  NULL,  
  MONTO_DEUDA   NUMERIC(10)  NULL,  
  FINVIG_CON   DATETIME  NULL,  
  DEU_REVISION  CHAR(1)   NULL,  
  TIPO_DEUDOR   CHAR(1)   NULL,  
  TIPO_CONTRATO  CHAR(1)   NULL,  
  MONTO_ASIG   NUMERIC(10)  NULL,  
  DEC_PERIODO   DATETIME  NULL,  
  COT_RUT    CHAR(10)  NULL,  
  EPA_RUT    CHAR(10)  NULL)  
  
  
 CREATE TABLE #RESP  
  (DDR_RUT   CHAR(10)  NULL,  
  DEU_ASIG_DESDE  DATETIME  NULL,  
  TIPO_CON_ACTUAL  VARCHAR(250) NULL,  
  ESTADO_VIG_CONTRATO VARCHAR(20)  NULL,  
  TIPO_DEUDOR   CHAR(1)   NULL,  
  MONTO_DEUDA   NUMERIC(15)  NULL,  
  MONTO_DEUDA_IP  NUMERIC(15)  NULL,  
  MONTO_DEUDA_DPP  NUMERIC(15)  NULL,  
  MONTO_DEUDA_DNP  NUMERIC(15)  NULL,  
  NRO_PER    NUMERIC(15)  NULL,  
  PRIMER_PER   DATETIME  NULL,  
  ULT_PER    DATETIME  NULL,  
  FINVIG_CON   DATETIME  NULL,  
  DEU_REVISION  CHAR(1)   NULL)  
  
 INSERT INTO #DEUDA_DB  
 EXEC spu_ges_cob_cartera_deuda_base @cob_codigo , 0  
  
  
 INSERT INTO #RESP  
 SELECT  DDR_RUT,  
    DEU_ASIG_DESDE,  
    CASE WHEN COT_RUT=DDR_RUT THEN TIPO_CONTRATO ELSE NULL END AS TIPO_CON_ACTUAL,  
    CASE WHEN COT_RUT=DDR_RUT THEN ESTADO_VIG_CONTRATO ELSE NULL END AS  ESTADO_VIG_CONTRATO,  
    TIPO_DEUDOR,  
    SUM(MONTO_DEUDA) AS MONTO_DEUDA,  
    SUM(CASE WHEN TIPO_DEUDA='IP' THEN MONTO_DEUDA ELSE 0 END) AS MONTO_DEUDA_IP,  
    SUM(CASE WHEN TIPO_DEUDA='DPP' THEN MONTO_DEUDA ELSE 0 END) AS MONTO_DEUDA_DPP,  
    SUM(CASE WHEN TIPO_DEUDA='DNP' THEN MONTO_DEUDA ELSE 0 END) AS MONTO_DEUDA_DNP,  
    COUNT ( DISTINCT DEC_PERIODO) AS NRO_PER,  
    MIN(DEC_PERIODO) AS PRIMER_PER,  
    MAX(DEC_PERIODO) AS ULT_PER,  
    CASE WHEN COT_RUT=DDR_RUT THEN FINVIG_CON ELSE NULL END AS FINVIG_CON,  
    DEU_REVISION   
 FROM  #DEUDA_DB  
 GROUP BY DDR_RUT,  
    DEU_ASIG_DESDE,  
    CASE WHEN COT_RUT=DDR_RUT THEN TIPO_CONTRATO ELSE NULL END,  
    CASE WHEN COT_RUT=DDR_RUT THEN ESTADO_VIG_CONTRATO ELSE NULL END,  
    TIPO_DEUDOR,  
    --TIPO_CONTRATO,  
    CASE WHEN COT_RUT=DDR_RUT THEN FINVIG_CON ELSE NULL END,  
    DEU_REVISION  
   
  
 SELECT DISTINCT R.DDR_RUT,  
   UPPER(DR.DDR_NOMBRE) AS DDR_NOMBRE,  
   CASE WHEN R.TIPO_DEUDOR='A' THEN 'AFILIADO'  
    WHEN R.TIPO_DEUDOR='E' THEN 'EMPLEADOR'  
    WHEN R.TIPO_DEUDOR='P' THEN 'EMP PUBLICA'  
   END AS TIPO_DEUDOR,  
   DEU_ASIG_DESDE,  
   TT.TTR_DESCRIP AS  TIPO_CON_ACTUAL,  
   ESTADO_VIG_CONTRATO,  
   MONTO_DEUDA,  
   MONTO_DEUDA_IP,  
   MONTO_DEUDA_DPP,  
   MONTO_DEUDA_DNP,  
   NRO_PER,  
   PRIMER_PER,  
   ULT_PER,  
   (SELECT COUNT(GESTION_COBRANZA.GEC_CORREL)   
    FROM GESTION_COBRANZA  WITH (NOLOCK)   
    WHERE GESTION_COBRANZA.COB_CODIGO = @cob_codigo  
    AND GESTION_COBRANZA.DDR_RUT = R.DDR_RUT  
    AND GESTION_COBRANZA.GEC_FECHA_GES < DEU_ASIG_DESDE ) AS NUM_GEST_ANT,  
   (SELECT COUNT(GESTION_COBRANZA.GEC_CORREL)   
    FROM GESTION_COBRANZA  WITH (NOLOCK)   
    WHERE GESTION_COBRANZA.COB_CODIGO = @cob_codigo  
    AND GESTION_COBRANZA.DDR_RUT = R.DDR_RUT  
    AND GESTION_COBRANZA.GEC_FECHA_GES >= DEU_ASIG_DESDE ) NUM_GEST_ACT,  
   (SELECT MAX(GESTION_COBRANZA.GEC_FECHA_GES)   
    FROM GESTION_COBRANZA  WITH (NOLOCK)   
    WHERE GESTION_COBRANZA.COB_CODIGO = @cob_codigo  
    AND GESTION_COBRANZA.DDR_RUT = R.DDR_RUT ) AS FEC_ULT_GEST,  
   FINVIG_CON,  
      
   (SELECT MAX(GESTION_COBRANZA.GEC_COMPROM_FECHA)   
    FROM GESTION_COBRANZA  WITH (NOLOCK)   
    WHERE  GESTION_COBRANZA.DDR_RUT = R.DDR_RUT AND TGC_CODIGO=29 ) AS FEC_COMPROMISO,  
     
   CASE (SELECT COUNT(GESTION_COBRANZA.GEC_CORREL)   
     FROM GESTION_COBRANZA  WITH (NOLOCK) JOIN TIPO_GESTION_COB WITH (NOLOCK) ON GESTION_COBRANZA.TGC_CODIGO=TIPO_GESTION_COB.TGC_CODIGO  
     WHERE (GESTION_COBRANZA.COB_CODIGO = @cob_codigo /*OR GESTION_COBRANZA.COB_CODIGO=3*/)  
     AND GESTION_COBRANZA.DDR_RUT = R.DDR_RUT  
     AND GESTION_COBRANZA.GEC_FECHA_GES >= DEU_ASIG_DESDE  
     AND TIPO_GESTION_COB.TGC_CLASIF='Cobranza'  
     AND  GEC_DIGITA<>'ASOTOG')   
   WHEN 0 THEN 0   
   ELSE 1 END AS GESTIONADO,  
   DEU_REVISION,  
   P.PROBABILIDAD_DE_PAGA,  
   P.PREDICCION_DIAS,  
   P.FECHA_PROCESO  
 FROM #RESP AS R   
  LEFT JOIN DEUDOR DR ON R.DDR_RUT=DR.DDR_RUT  
  LEFT JOIN TIPO_TRABAJADOR as TT ON TT.TTR_CODIGO=R.TIPO_CON_ACTUAL  
  LEFT JOIN BI_RESULTADOS_MLPGD AS P ON P.TIPO_DEUDOR=CASE WHEN R.TIPO_DEUDOR='A' THEN 'AFILIADO' WHEN R.TIPO_DEUDOR='E' THEN 'EMPLEADOR' ELSE '' END   
   AND P.RUT_DEUDOR=DR.DDR_RUT   
   AND P.FECHA_PROCESO=(SELECT MAX(FECHA_PROCESO) FROM BI_RESULTADOS_MLPGD AS P2 WHERE P2.RUT_DEUDOR=P.RUT_DEUDOR AND P2.TIPO_DEUDOR=P.TIPO_DEUDOR)  
 order by R.DDR_RUT  
  
  
END  