
--DROP TABLE GCO_ENVMSG_PROGRAMA

USE [ISAPRE]
GO

/****** Object:  Table [dbo].[GCO_ENVMSG_PROGRAMA]    Script Date: 28-07-2025 12:00:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GCO_ENVMSG_PROGRAMA](
	[EPR_CODIGO] [varchar](50) NOT NULL,
	[EPL_CODIGO] [varchar](50) NOT NULL,
	[EPR_DESCRIP] [varchar](500) NOT NULL,
	[EPR_TEMPLATE_API] [varchar](100) NULL,
	[EPR_TIPO_ENVIO] [char](1) NOT NULL,
	[EPR_INIVIG_ENVIO] [datetime] NOT NULL,
	[EPR_FINVIG_ENVIO] [datetime] NULL,
	[EPR_HORA_ENVIO] [datetime] NOT NULL,
	[EPR_LUNES] [char](1) NULL,
	[EPR_MARTES] [char](1) NULL,
	[EPR_MIERCOLES] [char](1) NULL,
	[EPR_JUEVES] [char](1) NULL,
	[EPR_VIERNES] [char](1) NULL,
	[EPR_SABADO] [char](1) NULL,
	[EPR_DOMINGO] [char](1) NULL,
 CONSTRAINT [PK_GCO_ENVMSG_PROGRAMA] PRIMARY KEY CLUSTERED 
(
	[EPR_CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GCO_ENVMSG_PROGRAMA]  WITH CHECK ADD  CONSTRAINT [FK_GCO_ENVM_REF_10501_GCO_ENVM] FOREIGN KEY([EPL_CODIGO])
REFERENCES [dbo].[GCO_ENVMSG_PLANTILLA] ([EPL_CODIGO])
GO

ALTER TABLE [dbo].[GCO_ENVMSG_PROGRAMA] CHECK CONSTRAINT [FK_GCO_ENVM_REF_10501_GCO_ENVM]
GO


