USE [ISAPRE]
GO

/****** Object:  Table [dbo].[GCO_ENV_MENSAJE_PROG_DET]    Script Date: 28-07-2025 12:54:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET](
	[EMD_ID] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[EPR_CODIGO] [varchar](50) NULL,
	[EMD_TIPO] [char](1) NOT NULL,
	[EMD_FECHA_ENVIO] [datetime] NULL,
	[EMD_HORA_ENVIO] [datetime] NULL,
	[EMD_LUNES] [char](1) NULL,
	[EMD_MARTES] [char](1) NULL,
	[EMD_MIERCOLES] [char](1) NULL,
	[EMD_JUEVES] [char](1) NULL,
	[EMD_VIERNES] [char](1) NULL,
	[EMD_SABADO] [char](1) NULL,
	[EMD_DOMINGO] [char](1) NULL,
 CONSTRAINT [PK_GCO_ENV_MENSAJE_PROG_DET] PRIMARY KEY CLUSTERED 
(
	[EMD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET] ADD  DEFAULT ('N') FOR [EMD_LUNES]
GO

ALTER TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET]  WITH CHECK ADD  CONSTRAINT [FK_GCO_ENV__REF_10501_GCO_ENVM] FOREIGN KEY([EPR_CODIGO])
REFERENCES [dbo].[GCO_ENVMSG_PROGRAMA] ([EPR_CODIGO])
GO

ALTER TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET] CHECK CONSTRAINT [FK_GCO_ENV__REF_10501_GCO_ENVM]
GO

ALTER TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET]  WITH CHECK ADD  CONSTRAINT [FK_GCO_ENV__REF_10501_GCO_ENVM3] FOREIGN KEY([EPR_CODIGO])
REFERENCES [dbo].[GCO_ENVMSG_PROGRAMA] ([EPR_CODIGO])
GO

ALTER TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET] CHECK CONSTRAINT [FK_GCO_ENV__REF_10501_GCO_ENVM3]
GO

ALTER TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET]  WITH CHECK ADD  CONSTRAINT [CKC_EMD_LUNES_GCO_ENV_] CHECK  (([EMD_LUNES]='N' OR [EMD_LUNES]='S'))
GO

ALTER TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET] CHECK CONSTRAINT [CKC_EMD_LUNES_GCO_ENV_]
GO

ALTER TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET]  WITH CHECK ADD  CONSTRAINT [CKC_EMD_TIPO_GCO_ENV_] CHECK  (([EMD_TIPO]='P' OR [EMD_TIPO]='U'))
GO

ALTER TABLE [dbo].[GCO_ENV_MENSAJE_PROG_DET] CHECK CONSTRAINT [CKC_EMD_TIPO_GCO_ENV_]
GO


