
[User Info]
UltimoLogin=MSANHUEZ

[CONNECT]
Isapre=MASVIDA
;Servidor=EVO-PASO
;Servidor=EVOLUTION
servidor=150.10.11.55
;Servidor=srv-nmv-qa01.masvida.cl
BaseDato=ISAPRE

[Instalacion]
SOURCE=\\mantencion_2000\last_version\mantencion
ejecutable=sistema_mantencion.exe
sistema=Mantencion
VERSION=28/01/2005 12:00:00
UPDATE=
impresion_duplex=SI

